/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Bank;

import java.awt.Frame;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class UpdateTransaksi extends javax.swing.JDialog {

    /**
     * Creates new form UpdateTransaksi
     */
    private String oldIdTransaksi;
    private Nasabah parentFrame;

    public UpdateTransaksi(Frame parent, boolean modal, String kode, String idn, String tanggal, String jenis, String jumlah) {
        super(parent, modal);
        initComponents();
        this.parentFrame = (Nasabah) parent;
        loadNasabahToComboBox();

        this.kode.setText(kode);
        this.idn.setSelectedItem(idn);
        try {
            java.util.Date tgl = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
            this.tanggal.setDate(tgl);
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.jenis.setSelectedItem(jenis);
        this.jumlah.setText(jumlah);
        this.oldIdTransaksi = kode;
    }

    private void loadNasabahToComboBox() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasLimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            List<Nasabah_1> listNasabah = em.createQuery("SELECT n FROM Nasabah_1 n", Nasabah_1.class).getResultList();
            idn.removeAllItems();

            for (Nasabah_1 n : listNasabah) {
                idn.addItem(n.getIdnasabah());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data nasabah: " + e.getMessage());
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        idn = new javax.swing.JComboBox<>();
        tanggal = new com.toedter.calendar.JDateChooser();
        jenis = new javax.swing.JComboBox<>();
        jumlah = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE TRANSAKSI");

        jLabel2.setText("KODE TRANSAKSI");

        jLabel3.setText("ID NASABAH");

        jLabel4.setText("TGL TRANSAKSI");

        jLabel5.setText("JENIS TRANSAKSI");

        jLabel6.setText("JUMLAH");

        idn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnActionPerformed(evt);
            }
        });

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setor", "Tarik" }));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kode)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jumlah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenis, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tanggal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(idn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(91, 91, 91))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnActionPerformed
        String selectedId = (String) idn.getSelectedItem();
        if (selectedId == null) {
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasLimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            Nasabah_1 nasabah = em.find(Nasabah_1.class, selectedId);
            if (nasabah == null) {
                JOptionPane.showMessageDialog(this,
                        "ID Nasabah tidak ditemukan di database!",
                        "Peringatan", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_idnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (kode.getText().trim().isEmpty() || idn.getSelectedItem() == null
                || tanggal.getDate() == null || jenis.getSelectedItem() == null
                || jumlah.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }

        String idTransaksiBaru = kode.getText().trim();
        String idNasabah = (String) idn.getSelectedItem();
        String jenisTransaksi = (String) jenis.getSelectedItem();
        java.util.Date tanggalUtil = tanggal.getDate();
        BigDecimal jumlahBig;

        try {
            jumlahBig = new BigDecimal(jumlah.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        EntityManagerFactory emf = null;
        EntityManager em = null;

        try {
            emf = Persistence.createEntityManagerFactory("TugasLimaPU");
            em = emf.createEntityManager();
            em.getTransaction().begin();

            Transaksi transaksi = em.find(Transaksi.class, oldIdTransaksi);

            Nasabah_1 nasabah = em.find(Nasabah_1.class, idNasabah);
            if (nasabah == null) {
                JOptionPane.showMessageDialog(this, "Nasabah tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            if (transaksi == null) {

                transaksi = new Transaksi();
                transaksi.setKodeTransaksi(idTransaksiBaru);
                transaksi.setTanggalTransaksi(new java.sql.Date(tanggalUtil.getTime()));
                transaksi.setJenisTransaksi(jenisTransaksi);
                transaksi.setJumlah(jumlahBig);
                transaksi.setIdnasabah(nasabah);
                em.persist(transaksi);
            } else {

                transaksi.setTanggalTransaksi(new java.sql.Date(tanggalUtil.getTime()));
                transaksi.setJenisTransaksi(jenisTransaksi);
                transaksi.setJumlah(jumlahBig);
                transaksi.setIdnasabah(nasabah);
                em.merge(transaksi);
            }

            BigDecimal saldo = nasabah.getSaldo();
            if ("Setor".equalsIgnoreCase(jenisTransaksi)) {
                saldo = saldo.add(jumlahBig);
            } else if ("Tarik".equalsIgnoreCase(jenisTransaksi)) {
                saldo = saldo.subtract(jumlahBig);
            }
            nasabah.setSaldo(saldo);

            em.merge(nasabah);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
            if (parentFrame != null) {
                parentFrame.tampilkanData();
                parentFrame.tampilkanDataTransaksi();
            }
            this.dispose();

        } catch (Exception e) {
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            if (em != null) {
                em.close();
            }
            if (emf != null) {
                emf.close();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> idn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kode;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
