/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Bank;

/**
 *
 * @author ACER
 */
import javax.swing.JFrame;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

public class InsertTransaksi extends javax.swing.JDialog {

    /**
     * Creates new form InsertTransaksi
     */
    public InsertTransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadNasabahToComboBox();
        setLocationRelativeTo(parent);
    }

    private Nasabah parentFrame;

    public InsertTransaksi(Nasabah parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadNasabahToComboBox();
        setLocationRelativeTo(parent);
        this.parentFrame = parent;
    }

    private void loadNasabahToComboBox() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasLimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            List<Nasabah_1> listNasabah = em.createQuery("SELECT n FROM Nasabah_1 n", Nasabah_1.class).getResultList();
            idn.removeAllItems();

            for (Nasabah_1 n : listNasabah) {
                idn.addItem(n.getIdnasabah());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data nasabah: " + e.getMessage());
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kode = new javax.swing.JTextField();
        idn = new javax.swing.JComboBox<>();
        tanggal = new com.toedter.calendar.JDateChooser();
        jenis = new javax.swing.JComboBox<>();
        jumlah = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("INSERT TRANSAKSI");

        jLabel2.setText("KODE TRANSAKSI");

        jLabel3.setText("ID NASABAH");

        jLabel4.setText("TGL TRANSAKSI");

        jLabel5.setText("JENIS TRANSAKSI");

        jLabel6.setText("JUMLAH");

        idn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnActionPerformed(evt);
            }
        });

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Setor", "Tarik" }));

        simpan.setText("INSERT");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(simpan))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kode)
                            .addComponent(idn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jumlah)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(idn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(simpan)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if (kode.getText().isEmpty()
                || idn.getSelectedItem() == null
                || tanggal.getDate() == null
                || jenis.getSelectedItem() == null
                || jumlah.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }

        String kodeTransaksi = kode.getText().trim();
        String idNasabah = ((String) idn.getSelectedItem()).trim();
        String jenisTransaksi = ((String) jenis.getSelectedItem()).trim();

        java.util.Date utilDate = tanggal.getDate();
        java.sql.Date sqlTanggal = new java.sql.Date(utilDate.getTime());

        BigDecimal nilaiJumlah;
        try {
            nilaiJumlah = new BigDecimal(this.jumlah.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasLimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            em.getTransaction().begin();

            Transaksi existing = em.find(Transaksi.class, kodeTransaksi);
            if (existing != null) {
                JOptionPane.showMessageDialog(this, "Kode transaksi sudah ada!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            Nasabah_1 nasabah = em.find(Nasabah_1.class, idNasabah);
            if (nasabah == null) {
                JOptionPane.showMessageDialog(this, "Nasabah tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            Transaksi transaksi = new Transaksi();
            transaksi.setKodeTransaksi(kodeTransaksi);
            transaksi.setIdnasabah(nasabah);
            transaksi.setJenisTransaksi(jenisTransaksi);
            transaksi.setTanggalTransaksi(sqlTanggal);
            transaksi.setJumlah(nilaiJumlah);

            em.persist(transaksi);

            BigDecimal saldoSekarang = nasabah.getSaldo();
            BigDecimal saldoBaru;

            if (jenisTransaksi.equalsIgnoreCase("Setor")) {
                saldoBaru = saldoSekarang.add(nilaiJumlah);
            } else if (jenisTransaksi.equalsIgnoreCase("Tarik")) {

                if (saldoSekarang.compareTo(nilaiJumlah) < 0) {
                    JOptionPane.showMessageDialog(this, "Saldo tidak cukup untuk penarikan!", "Error", JOptionPane.ERROR_MESSAGE);
                    em.getTransaction().rollback();
                    return;
                }
                saldoBaru = saldoSekarang.subtract(nilaiJumlah); 
            } else {
                JOptionPane.showMessageDialog(this, "Jenis transaksi tidak valid!");
                em.getTransaction().rollback();
                return;
            }

            nasabah.setSaldo(saldoBaru);
            em.merge(nasabah);

            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan dan saldo diperbarui!");

            if (parentFrame != null) {
                parentFrame.tampilkanData();
                parentFrame.tampilkanDataTransaksi();
            }

            this.dispose();

        } catch (Exception ex) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void idnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnActionPerformed
        String selectedId = (String) idn.getSelectedItem();
        if (selectedId == null) {
            return;
        }

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("TugasLimaPU");
        EntityManager em = emf.createEntityManager();

        try {
            Nasabah_1 nasabah = em.find(Nasabah_1.class, selectedId);
            if (nasabah == null) {
                JOptionPane.showMessageDialog(this,
                        "ID Nasabah tidak ditemukan di database!",
                        "Peringatan", JOptionPane.WARNING_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_idnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> idn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kode;
    private javax.swing.JButton simpan;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
