/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bank;

import java.io.BufferedReader;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileSystemView;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import javax.persistence.Persistence;

/**
 *
 * @author ACER
 */
public class Nasabah extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/Bank";
    String user = "postgres";
    String password = "1234";

    /**
     * Creates new form Nasabah
     */
    public Nasabah() {

        initComponents();
        tampilkanData();
        tampilkanDataTransaksi();
        
    }

    public void tampilkanData() {
        EntityManager em = Persistence.createEntityManagerFactory("TugasLimaPU").createEntityManager();

        TypedQuery<Nasabah_1> q = em.createNamedQuery("Nasabah_1.findAll", Nasabah_1.class);
        List<Nasabah_1> hasil = q.getResultList();

        DefaultTableModel tbn = new DefaultTableModel(
                new String[]{"ID NASABAH", "NAMA", "ALAMAT", "SALDO"}, 0
        );

        for (Nasabah_1 data : hasil) {
            Object[] baris = new Object[4];
            baris[0] = data.getIdnasabah();
            baris[1] = data.getNama();
            baris[2] = data.getAlamat();
            baris[3] = data.getSaldo();
            tbn.addRow(baris);
        }

        Tabel.setModel(tbn);
        em.close();
    }

    public void tampilkanDataTransaksi() {
        EntityManager em = Persistence.createEntityManagerFactory("TugasLimaPU").createEntityManager();

        try {
            TypedQuery<Transaksi> q = em.createNamedQuery("Transaksi.findAll", Transaksi.class);
            List<Transaksi> hasil = q.getResultList();

            DefaultTableModel tbn = new DefaultTableModel(
                    new String[]{"Kode Transaksi", "Id Nasabah", "Tanggal Transaksi", "Jenis Transaksi", "Jumlah"}, 0
            );

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");

            for (Transaksi data : hasil) {
                Object[] baris = new Object[5];
                baris[0] = data.getKodeTransaksi();
                baris[1] = data.getIdnasabah().getIdnasabah();

                if (data.getTanggalTransaksi() != null) {
                    baris[2] = sdf.format(data.getTanggalTransaksi());
                } else {
                    baris[2] = "";
                }

                baris[3] = data.getJenisTransaksi();
                baris[4] = data.getJumlah();
                tbn.addRow(baris);
            }

            tabelTransaksi.setModel(tbn);
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal menampilkan data transaksi: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            em.close();
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Data Nasabah");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jButton4.setText("Cetak");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        jButton5.setText("Upload");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Nasabah", "Nama", "Alamat", "Saldo"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel);

        tabPane.addTab("Nasabah", jScrollPane1);

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Tranaksi", "Id Nasabah", "Tanggal Transaksi", "Jenis Transaksi", "Jumlah"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelTransaksi);

        tabPane.addTab("Transaksi", jScrollPane2);

        getContentPane().add(tabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 470, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int index = tabPane.getSelectedIndex();
        String title = tabPane.getTitleAt(index);

        if (title.equals("Nasabah")) {
            int baris = Tabel.getSelectedRow();
            if (baris >= 0) {
                String idNasabah = Tabel.getValueAt(baris, 0).toString();
                DeleteDialog dialog = new DeleteDialog(this, true, idNasabah);
                dialog.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data nasabah dulu!");
            }

        } else if (title.equals("Transaksi")) {
            int baris = tabelTransaksi.getSelectedRow();
            if (baris >= 0) {
                String idTransaksi = tabelTransaksi.getValueAt(baris, 0).toString();
                DeleteTransaksi dialog1 = new DeleteTransaksi(this, true, idTransaksi);
                dialog1.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data transaksi dulu!");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = tabPane.getSelectedIndex();
        String title = tabPane.getTitleAt(index);

        if (title.equals("Nasabah")) {
            InsertDialog dialog = new InsertDialog(this, true);
            dialog.setVisible(true);
        } else if (title.equals("Transaksi")) {
            InsertTransaksi dialog2 = new InsertTransaksi(this, true);
            dialog2.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int index = tabPane.getSelectedIndex();
        String title = tabPane.getTitleAt(index);

        if (title.equals("Nasabah")) {
            int baris = Tabel.getSelectedRow();
            if (baris >= 0) {
                String idNasabah = Tabel.getValueAt(baris, 0).toString();
                String nama = Tabel.getValueAt(baris, 1).toString();
                String alamat = Tabel.getValueAt(baris, 2).toString();
                String saldo = Tabel.getValueAt(baris, 3).toString();

                UpdateDialog dialog = new UpdateDialog(this, true, idNasabah, nama, alamat, saldo);
                dialog.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data nasabah yang ingin diupdate!");
            }

        } else if (title.equals("Transaksi")) {
            int baris = tabelTransaksi.getSelectedRow();
            if (baris >= 0) {
                String kode = tabelTransaksi.getValueAt(baris, 0).toString();
                String idn = tabelTransaksi.getValueAt(baris, 1).toString();
                String tanggal = tabelTransaksi.getValueAt(baris, 2).toString();
                String jenis = tabelTransaksi.getValueAt(baris, 3).toString();
                String jumlah = tabelTransaksi.getValueAt(baris, 4).toString();

                UpdateTransaksi dialogTransaksi = new UpdateTransaksi(this, true,
                        kode, idn, tanggal, jenis, jumlah);
                dialogTransaksi.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih data transaksi yang ingin diupdate!");
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked

        try {
            int row = Tabel.getSelectedRow();
            if (row >= 0) {

                String id = Tabel.getValueAt(row, 0).toString();
                String nama = Tabel.getValueAt(row, 1).toString();
                String alamat = Tabel.getValueAt(row, 2).toString();
                String saldo = Tabel.getValueAt(row, 3).toString();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat memilih data: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_TabelMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int index = tabPane.getSelectedIndex();
        String title = tabPane.getTitleAt(index);

        String reportPath = "";

        if (title.equalsIgnoreCase("Nasabah")) {
            reportPath = "C:\\Users\\ACER\\NetBeansProjects\\TugasLima\\src\\Bank\\LaporanKeungan.jasper";
        } else if (title.equalsIgnoreCase("Transaksi")) {
            reportPath = "C:\\Users\\ACER\\NetBeansProjects\\TugasLima\\src\\Bank\\LaporanTransaksi.jasper";
        } else {
            JOptionPane.showMessageDialog(this, "Tab tidak memiliki laporan.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            Class.forName("org.postgresql.Driver");
            java.sql.Connection conn = java.sql.DriverManager.getConnection(
                    "jdbc:postgresql://localhost:5432/Bank",
                    "postgres",
                    "1234"
            );

            JasperReport reports = (JasperReport) JRLoader.loadObjectFromFile(reportPath);
            java.util.Map<String, Object> parameters = new java.util.HashMap<>();
            JasperPrint jprint = JasperFillManager.fillReport(reports, parameters, conn);

            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);

            conn.close();

        } catch (Exception ex) {
            Logger.getLogger(Nasabah.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat mencetak laporan:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int index = tabPane.getSelectedIndex();
        String title = tabPane.getTitleAt(index);

        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File filePilihan = jfc.getSelectedFile();
        System.out.println("File dipilih: " + filePilihan.getAbsolutePath());

        BufferedReader br = null;
        EntityManagerFactory emf = null;
        EntityManager em = null;

        try {
            br = new BufferedReader(new FileReader(filePilihan));
            emf = Persistence.createEntityManagerFactory("TugasLimaPU");
            em = emf.createEntityManager();

            em.getTransaction().begin();

           
            br.mark(4096);
            String header = br.readLine();
            if (header == null) {
                JOptionPane.showMessageDialog(null, "File CSV kosong!");
                return;
            }

            String pemisah;
            if (header.contains(";")) {
                pemisah = ";";
            } else if (header.contains(",")) {
                pemisah = ",";
            } else if (header.contains("\t")) {
                pemisah = "\t";
            } else {
                pemisah = ";"; 
            }
            br.reset(); 

            
            if (title.equalsIgnoreCase("Nasabah")) {
                String baris;
                while ((baris = br.readLine()) != null) {
                    if (baris.trim().isEmpty()) {
                        continue;
                    }
                    String[] data = baris.split(pemisah);
                    if (data.length < 4) {
                        continue; 
                    }
                    String id = data[0].trim();
                    String nama = data[1].trim();
                    String alamat = data[2].trim();
                    String saldoStr = data[3].trim();

                    if (!id.isEmpty() && !nama.isEmpty() && !alamat.isEmpty() && !saldoStr.isEmpty()) {
                        double saldo = Double.parseDouble(saldoStr.replace(",", "."));

                        
                        if (em.find(Nasabah_1.class, id) != null) {
                            System.out.println(" Nasabah " + id + " sudah ada, dilewati.");
                            continue;
                        }

                        Nasabah_1 n = new Nasabah_1();
                        n.setIdnasabah(id);
                        n.setNama(nama);
                        n.setAlamat(alamat);
                        n.setSaldo(BigDecimal.valueOf(saldo));

                        em.persist(n);
                    }
                }

                em.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Upload selesai!");
                tampilkanData(); 
            } 
            else if (title.equalsIgnoreCase("Transaksi")) {
                int berhasil = 0;
                int gagal = 0;

                DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
                

                String baris;
                while ((baris = br.readLine()) != null) {
                    if (baris.trim().isEmpty()) {
                        continue;
                    }

                    String[] data = baris.split(pemisah);
                    if (data.length < 5) {
                        System.out.println("Kolom kurang: " + baris);
                        gagal++;
                        continue;
                    }

                    try {
                        String idTransaksi = data[0].trim();
                        String idNasabah = data[1].trim();
                        String tanggalStr = data[2].trim();
                        String jenis = data[3].trim();
                        String jumlahStr = data[4].trim();

                        jumlahStr = jumlahStr.replace(".", "").replace(",", ".");
                        BigDecimal jumlah = new BigDecimal(jumlahStr);

                        Date tanggal;
                        if (tanggalStr.contains("-")) {
                            tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalStr);
                        } else if (tanggalStr.contains("/")) {
                            tanggal = new SimpleDateFormat("dd/MM/yyyy").parse(tanggalStr);
                        } else {
                            throw new IllegalArgumentException("Format tanggal tidak dikenali: " + tanggalStr);
                        }

                        Nasabah_1 nasabah = em.find(Nasabah_1.class, idNasabah);
                        if (nasabah == null) {
                            System.out.println(" Nasabah " + idNasabah + " tidak ditemukan!");
                            gagal++;
                            continue;
                        }

                        if (em.find(Transaksi.class, idTransaksi) != null) {
                            System.out.println("️ Transaksi " + idTransaksi + " sudah ada, dilewati.");
                            gagal++;
                            continue;
                        }

                        Transaksi t = new Transaksi();
                        t.setKodeTransaksi(idTransaksi);
                        t.setIdnasabah(nasabah);
                        t.setTanggalTransaksi(tanggal);
                        t.setJenisTransaksi(jenis);
                        t.setJumlah(jumlah);
                        em.persist(t);

                        if ("Setor".equalsIgnoreCase(jenis)) {
                            nasabah.setSaldo(nasabah.getSaldo().add(jumlah));
                        } else if ("Tarik".equalsIgnoreCase(jenis)) {
                            nasabah.setSaldo(nasabah.getSaldo().subtract(jumlah));
                        }
                        em.merge(nasabah);

                        berhasil++;

                    } catch (Exception eRow) {
                        gagal++;
                        System.out.println(" Gagal memproses baris: " + baris);
                        eRow.printStackTrace();
                    }
                }

                em.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Upload selesai!");
                tampilkanData();
                tampilkanDataTransaksi();
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            if (em != null && em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException e) {
            }
            if (em != null) {
                em.close();
            }
            if (emf != null) {
                emf.close();
            }
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked

    }//GEN-LAST:event_tabelTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nasabah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nasabah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
